---
- name: system Reboot !!!
  hosts: masters
  become: yes
  any_errors_fatal: true
  tasks:
    - name: "<masters:System> Reboot"
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
